# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateMixture <- function(Y_, k_, nIter_, seed_, alpha_) {
    .Call('_pottsMixture_estimateMixture', PACKAGE = 'pottsMixture', Y_, k_, nIter_, seed_, alpha_)
}

estimateMixtureWithErrors <- function(Y_, Y_test, k_, nIter_, seed_, alpha_) {
    .Call('_pottsMixture_estimateMixtureWithErrors', PACKAGE = 'pottsMixture', Y_, Y_test, k_, nIter_, seed_, alpha_)
}

estimateInitializedMixture <- function(Y_, k_, nIter_, seed_, alpha_, initialPYZ_, initialH_) {
    .Call('_pottsMixture_estimateInitializedMixture', PACKAGE = 'pottsMixture', Y_, k_, nIter_, seed_, alpha_, initialPYZ_, initialH_)
}

estimateInitializedMixturewithErrors <- function(Y_, Y_test, k_, nIter_, seed_, alpha_, initialPYZ_, initialH_) {
    .Call('_pottsMixture_estimateInitializedMixturewithErrors', PACKAGE = 'pottsMixture', Y_, Y_test, k_, nIter_, seed_, alpha_, initialPYZ_, initialH_)
}

gibbsSample <- function(k_, edge1_, start1_, end1_, seed_, nIter_, offDiagonal_, fullPath_, h_, correlations_) {
    .Call('_pottsMixture_gibbsSample', PACKAGE = 'pottsMixture', k_, edge1_, start1_, end1_, seed_, nIter_, offDiagonal_, fullPath_, h_, correlations_)
}

EMSA <- function(Y_, k_, edge1_, start1_, end1_, seed_, constantIterations_, decreasingIterations_, decreasingStart_, scalarCorrelations_, stepSize_, alpha_, stochasticGradient_, surrogate_) {
    .Call('_pottsMixture_EMSA', PACKAGE = 'pottsMixture', Y_, k_, edge1_, start1_, end1_, seed_, constantIterations_, decreasingIterations_, decreasingStart_, scalarCorrelations_, stepSize_, alpha_, stochasticGradient_, surrogate_)
}

initializedEMSA <- function(Y_, k_, edge1_, start1_, end1_, seed_, constantIterations_, decreasingIterations_, decreasingStart_, scalarCorrelations_, stepSize_, alpha_, stochasticGradient_, surrogate_, initialH_, initialCorrelations_, initialMu_) {
    .Call('_pottsMixture_initializedEMSA', PACKAGE = 'pottsMixture', Y_, k_, edge1_, start1_, end1_, seed_, constantIterations_, decreasingIterations_, decreasingStart_, scalarCorrelations_, stepSize_, alpha_, stochasticGradient_, surrogate_, initialH_, initialCorrelations_, initialMu_)
}

cv_posteriorPredictive <- function(YTrain_, YTest_, edge1_, start1_, end1_, seed_, nIter_, nBurn_, H_, muParameter_, correlations_) {
    .Call('_pottsMixture_cv_posteriorPredictive', PACKAGE = 'pottsMixture', YTrain_, YTest_, edge1_, start1_, end1_, seed_, nIter_, nBurn_, H_, muParameter_, correlations_)
}

